---
encrypt:
  key: juhas
server:
  port: 8001
spring:
  config:
    name: configserver
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: file:///home/huta/workspace/java/springCloud
          #uri: https://github.com/HubertTatar/sbms.git
          search-paths: config
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8000/eureka/

#security:
#  user:
#    password: secret
#    name: app