server:
  port: 8003
spring:
  rabbitmq:
    host: localhost
    port: 5672
  jpa:
    database-platform: H2
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type: trace